### ISSUE TITLE
Error while executing generate_expert_demo.py

### ISSUE THREAD

**Issue by mehreenjabeen** [YuanGongND/realtime-adversarial-attack#2]
Hi,

Running  command "_python generate_expert_demo.py_" throws the error:
`Traceback (most recent call last):
  File "generate_expert_demo.py", line 18, in <module>
    _, newFolderName, gpuI = argv
ValueError: not enough values to unpack (expected 3, got 1)`

Seems some arguments need to be passed. Please help.

Also, in line 251 of generate_expert_demo.py, what is the path that needs to be set in _base_path_ variable. Is it the path of dataset that is downloaded or just 75% of downloaded dataset as it is mentioned in your paper that only 75% of the data is used to train the attack model.

Thanks,

**Comment by mehreenjabeen** [comment]
I tried to run "_python generate_expert_demo.py attackModel 0_"
But it gave the below error: 

`Traceback (most recent call last):
  File "generate_expert_demo.py", line 54, in <module>
    shutil.copy('formal_generate.py', newFolderName)
  File "/usr/lib/python3.6/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '_formal_generate.py_'
`

Which file need to be copied, there is no such file namely _formal_generate.py_ in the repo.

**Comment by sultanoid** [comment]
Have you got the file formal_generate.py in the repo? I cant find it. Please help me.
